defaults: &defaults
  update_supervisor_params:
    - supervisor
    - leader
  languages:
    en: "en"
    jp: "ja"
  tasks:
    statuses:
      new: 0
      in_progress: 1
      resolved: 2
      closed: 3
  course:
    init: 0
  flag_size: "20x15"
  image_user_size: "50x50"
  image_profile: "150x150"
  image_activity: "30x30"
  image_user_subject: "100x100"
  image_subject_size: "220x220"
  image_course_size: "220x220"
  finish: "finish"
  finished: "finished"
  date_format: "%H:%M:%S %-d %B %Y"
  date_course_format: "%-d %B %Y"
  course_subject:
    finish: "finish"
    start: "progress"
  form:
    field_size: 50
  position:
    check_position: 0
    index: 1
  roles:
    trainer: "trainer"
    actions:
      - "create"
      - "read"
      - "update"
      - "destroy"
  hours_working_day: 8
  image_size: "100x100"
  user_course_image_size: "128x128"
  admin_user_course_image_size: "40x40"
  number_user_display: 4
  tabs:
    overview: "overview"
    subjects: "subjects"
    trainees: "trainees"
    trainers: "trainers"
    course: "courses"
    course_master: "course_masters"
    evaluation_templete: "evaluation_templetes"
    rank: "ranks"
    evaluation: "evaluations"
    university: "university"
    status: "status"
    type: "user_type"
    user_profile: "User profiles"
    user_progress: "User progress"
    user: "user"
  default_password: 12345678
development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
